export const CREATEPOST_BEGIN = "CREATEPOST_BEGIN";
export const CREATEPOST_SUCCESS = "CREATEPOST_SUCCESS";
export const CREATEPOST_FAILURE = "CREATEPOST_FAILURE";

export const FETCH_ALLPOST_BEGIN = "FETCH_ALLPOST_BEGIN";
export const FETCH_ALLPOST_SUCCESS = "FETCH_ALLPOST_SUCCESS";
export const FETCH_ALLPOST_FAILURE = "FETCH_ALLPOST_FAILURE";

export const FETCH_POST_BEGIN = "FETCH_POST_BEGIN";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE";

export const DELETE_POST_BEGIN = "DELETE_POST_BEGIN";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const UPDATE_LIKECOMMENT_POST_BEGIN = "UPDATE_LIKECOMMENT_POST_BEGIN";
export const UPDATE_LIKECOMMENT_POST_SUCCESS =
  "UPDATE_LIKECOMMENT_POST_SUCCESS";
export const UPDATE_LIKECOMMENT_POST_FAILURE =
  "UPDATE_LIKECOMMENT_POST_FAILURE";

export const FETCH_USER_BEGIN = "FETCH_USER_BEGIN";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const FETCH_ALLUSER_BEGIN = "FETCH_ALLUSER_BEGIN";
export const FETCH_ALLUSER_SUCCESS = "FETCH_ALLUSER_SUCCESS";
export const FETCH_ALLUSER_FAILURE = "FETCH_ALLUSER_FAILURE";

export const FETCH_USERBYUSERNAME_BEGIN = "FETCH_USERBYUSERNAME_BEGIN";
export const FETCH_USERBYUSERNAME_SUCCESS = "FETCH_USERBYUSERNAME_SUCCESS";
export const FETCH_USERBYUSERNAME_FAILURE = "FETCH_USERBYUSERNAME_FAILURE";

export const UPDATEUSER_BEGIN = "UPDATEUSER_BEGIN";
export const UPDATEUSER_SUCCESS = "UPDATEUSER_SUCCESS";
export const UPDATEUSER_FAILURE = "UPDATEUSER_FAILURE";

export const UPDATEUSER_PHOTO_BEGIN = "UPDATEUSER_PHOTO_BEGIN";
export const UPDATEUSER_PHOTO_SUCCESS = "UPDATEUSER_PHOTO_SUCCESS";
export const UPDATEUSER_PHOTO_FAILURE = "UPDATEUSER_PHOTO_FAILURE";

export const CREATESTORY_BEGIN = "CREATESTORY_BEGIN";
export const CREATESTORY_SUCCESS = "CREATESTORY_SUCCESS";
export const CREATESTORY_FAILURE = "CREATESTORY_FAILURE";

export const FETCH_STORY_BEGIN = "FETCH_STORY_BEGIN";
export const FETCH_STORY_SUCCESS = "FETCH_STORY_SUCCESS";
export const FETCH_STORY_FAILURE = "FETCH_STORY_FAILURE";

export const FETCH_ALL_STORY_BEGIN = "FETCH_ALL_STORY_BEGIN";
export const FETCH_ALL_STORY_SUCCESS = "FETCH_ALL_STORY_SUCCESS";
export const FETCH_ALL_STORY_FAILURE = "FETCH_ALL_STORY_FAILURE";

export const DELETESTORY_BEGIN = "DELETESTORY_BEGIN";
export const DELETESTORY_SUCCESS = "DELETESTORY_SUCCESS";
export const DELETESTORY_FAILURE = "DELETESTORY_FAILURE";

export const SET_CREATESTORY_DETAILS = "SET_CREATESTORY_DETAILS";
export const CLEAR_CREATESTORY_DETAILS = "CLEAR_CREATESTORY_DETAILS";

export const CLEAR_CREATEDSTORY_DETAILS = "CLEAR_CREATEDSTORY_DETAILS";
