export const CREATEPOST_BEGIN = "CREATEPOST_BEGIN";
export const CREATEPOST_SUCCESS = "CREATEPOST_SUCCESS";
export const CREATEPOST_FAILURE = "CREATEPOST_FAILURE";

export const FETCH_ALLPOST_BEGIN = "FETCH_ALLPOST_BEGIN";
export const FETCH_ALLPOST_SUCCESS = "FETCH_ALLPOST_SUCCESS";
export const FETCH_ALLPOST_FAILURE = "FETCH_ALLPOST_FAILURE";

export const FETCH_POST_BEGIN = "FETCH_POST_BEGIN";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE";

export const DELETE_POST_BEGIN = "DELETE_POST_BEGIN";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";
