export const CREATEPOST_BEGIN = "CREATEPOST_BEGIN";
export const CREATEPOST_SUCCESS = "CREATEPOST_SUCCESS";
export const CREATEPOST_FAILURE = "CREATEPOST_FAILURE";

export const FETCH_ALLPOST_BEGIN = "FETCH_ALLPOST_BEGIN";
export const FETCH_ALLPOST_SUCCESS = "FETCH_ALLPOST_SUCCESS";
export const FETCH_ALLPOST_FAILURE = "FETCH_ALLPOST_FAILURE";
